server:
  port: 8080

mysql:
  host: 127.0.0.1
  port: 3308
  user: root
  password: "123456"
  database: feed_system_video

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0

jwt:
  secret: "feedSystem_video-dev-secret-key"
  access_ttl: 900       # 15分钟（秒）
  refresh_ttl: 604800    # 7天（秒）go get github.com/redis/go-redis/v9